### ISSUE TITLE
Make repo public

### ISSUE THREAD

**Issue by dkales** [TaceoLabs/co-snarks#99]
- [x] Readme
  - [x] Link to docs
  - [x] Usage
  - [x] Install
  - [x] LICENSE-GPL3.0, LICENSE-MIT, LICENSE-Apache2.0
- [x] Update/merge docs #67 
- [ ] Deny missing docs #60 
- [x] Build binaries automatically on release #94
